// <auto-generated />
using System;
using AirlineTicketReservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineTicketReservation.API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241010231455_AddRoleToPassenger")]
    partial class AddRoleToPassenger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineTicketReservation.Models.LoyaltyProgram", b =>
                {
                    b.Property<Guid>("LoyaltyNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("int");

                    b.HasKey("LoyaltyNumber");

                    b.HasIndex("PassengerId")
                        .IsUnique();

                    b.ToTable("LoyaltyProgram");
                });

            modelBuilder.Entity("AirlineTicketReservation.Models.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("AirlineTicketReservation.Models.LoyaltyProgram", b =>
                {
                    b.HasOne("AirlineTicketReservation.Models.Passenger", "Passenger")
                        .WithOne("LoyaltyProgram")
                        .HasForeignKey("AirlineTicketReservation.Models.LoyaltyProgram", "PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AirlineTicketReservation.Models.Passenger", b =>
                {
                    b.Navigation("LoyaltyProgram");
                });
#pragma warning restore 612, 618
        }
    }
}
